<a href="https://colab.research.google.com/github/soundharyajanagam/task1/blob/main/soundharya_of_task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#How do I randomly select rows from NumPy array?

create an array of 50 and reshape it into 5 rows and 10 columns



In [5]:
import numpy as np
ar = np.arange(0,50)
rsp = ar.reshape(5,10)
print(rsp)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


#Convert Numpy array to JSON

Array to JSON

In [8]:
import numpy as np
import json
arr = np.array([2,5,7,9,11,13])
arr_lst = arr.tolist()
jsonar = json.dumps(arr_lst)
print(jsonar)

[2, 5, 7, 9, 11, 13]


#How do you replace items that satisfy a condition with another value in Numpy array?

Replace all elements which are greater than 30 to 0

input:- [49, 7, 44, 27, 13, 35, 71]

In [6]:
arr = np.array([49,7,44,27,13,35,71])
print(arr>30)

[ True False  True False False  True  True]


#How to count frequency of unique values in a NumPy array in Python?

Find number of times a value appears in the list

sample input:- [9, 7, 4, 7, 3, 5, 9]

In [9]:
import numpy as np

arr = np.array([9, 7, 4, 7, 3, 5, 9])

uniq_val, counts = np.unique(arr, return_counts=True)

freqny = dict(zip(uniq_val, counts))

print(freqny)

{3: 1, 4: 1, 5: 1, 7: 2, 9: 2}


In [14]:
num = [9,7,4,7,3,5,9]
val = 7
count = num.count(val)
print(count)

2


#read the data from the group

explore the data

1. check for null values
2. check for duplicate values
3. check for dtype corrections
4. rename the columns date and time with "Date"  and "Time
5. By Using the iloc print 0:5 rows and 1,3,5 column indexes
6. convert df["stop_datetime"] to to_datetime format